[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "Luvdis"
description = "Pure-Python Game Boy Advance Disassembler"
readme = "README.md"
authors = [
    {name = "Ariel A", email = "24759293+aarant@users.noreply.github.com"},
]
dependencies = [
    "click~=7.0",
    "click-default-group",
    "tqdm>=4.0.0",
]
license = "MIT"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Topic :: Software Development :: Disassemblers",
    "Topic :: System :: Hardware",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9"
]
requires-python = ">= 3.6"
dynamic = ["version"]

[project.scripts]
luvdis = "luvdis.__main__:main"

[tool.setuptools]
packages = ["luvdis", "luvdis.test"]

[tool.setuptools.dynamic]
version = {attr = "luvdis.__version__"}

[tool.setuptools.package-data]
"*" = ["*.inc", "*.pickle"]

[project.urls]
Repository = "https://github.com/aarant/luvdis"