name: Publish Python package

on:
  push:
    tags:
      - 'v*'

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
  pyinstall:
    name: Build Windows executable
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Get version
        id: tag_name
        uses: olegtarasov/get-tag@v2.1
        with:
          tagRegex: "v(.*)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build executable
        run: |
          python pyinstall.py
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.tag_name.outputs.tag }}
          release_name: v${{ steps.tag_name.outputs.tag }}
          draft: true
          prerelease: false
      - name: Upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/Luvdis-${{ steps.tag_name.outputs.tag }}.exe
          asset_name: Luvdis-${{ steps.tag_name.outputs.tag }}.exe
          asset_content_type: application/zip
